modLoader = "javafml"
loaderVersion = "[38,)"

license = "${mod_license}"
issueTrackerURL = "${mod_issues}"

[[mods]]
    modId = "${mod_id}"
    version = "${mod_version}"
    displayName = "${mod_name}"
    displayURL = "${mod_url}"
    logoFile = "logo.png"
    authors = "${mod_author}"
    description = "${mod_description}"
    credits = "Motschen, TeamMidnightDust"
