modLoader = "javafml"
loaderVersion="[1,)"
license = "${mod_license}"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
displayURL = "${mod_url}"
logoFile = "logo.png"
authors = "${mod_author}"
description = "${mod_description}"
credits = "Motschen, TeamMidnightDust"
